### ISSUE TITLE
Latest version behind

### ISSUE THREAD

**Issue by robflate** [Marginal/docker-get_iplayer#1]
Hi,

Thanks for the docker image. The latest version of get_iplayer is 3.22 released 10 days ago but this image contains 3.21. The dockerfile pulls https://api.github.com/repos/get-iplayer/get_iplayer/releases/latest which says it's 3.22 but the webgui shows 3.21.

The readme.md says it auto updates. Is there anything I need to do to force it to update?

Thanks again,
Rob.

**Comment by asjmcguire** [comment]
Mine was at v3.17. I tried executing the update commands in /etc/periodic/daily/ manually and it did nothing, so I removed the quiet flags from the wget command and ran them individually to see what was going on - and wget is saying 400 bad request.

I manually used wget to download 
`
wget -O 'get_iplayer-322' https://api.github.com/repos/get-iplayer/get_iplayer/tarball/v3.22
tar -zxf ./get_iplayer-322
cd get-iplayer-get_iplayer-50a6051/
install -m 755 -t /usr/local/bin ./get_iplayer ./get_iplayer.cgi
`
and then deleted the downloaded file and restarted the docker container, it was then running v3.22 - it's probably worth double checking that the update commands are piping the right things to each other.

For me the command `wget -qO - "`wget -qO - 'https://api.github.com/repos/get-iplayer/get_iplayer
/releases/latest' | jq -r .tarball_url`"` does not work, but `wget -qO - 'https://api.github.com/repos/get-iplayer/get_iplayer/releases/latest' | jq -r .tarball_url | wget -i -` does successfully download v3.22

**Comment by Marginal** [comment]
The get_iplayer version does update, but the web frontend doesn't use the new version until you stop and restart the container. This isn't usually a problem since the web frontend rarely changes (the last material change was [over a year ago](https://github.com/get-iplayer/get_iplayer/commit/be40aeef966f7ce1c253f30a776cfa95570f9968#diff-fe8838ba68195c9c91f1413023602b47)), but it *is* confusing and could be a problem in future.

**Comment by asjmcguire** [comment]
v3.22 is required to refresh the feeds since changes happened at the BBC site. and I can absolutely confirm that until I manually updated the get_iplayer binary - it was unusable, no matter how many times I restarted the container.
