### ISSUE TITLE
Hourly Update

### ISSUE THREAD

**Issue by meakajon** [Marginal/docker-get_iplayer#2]
Hi,

Can a line be added to the hourly cron job to refresh the get_iplayer cache.

"su-exec $PUID:$PGID /usr/local/bin/get_iplayer --refresh --quiet 2>> /var/log/get_iplayer.log"

Cheers

**Comment by Marginal** [comment]
I think this can be effectively achieved by setting `expiry 3540` in your .get_iplayer/options file ?

**Comment by slimgym** [comment]
I noticed this build has no separate refresh call but the cache is refreshed as can be seen in the pvr run log file. It appears get_iplayer refreshes by default every 4 hours even when called with the pvr option (https://github.com/get-iplayer/get_iplayer/wiki/cache). 

This is a great build, much appreciated the time and effort put in. Flawless migration to docker from standalone. Thank you.
