### ISSUE TITLE
wget: error getting response: Connection reset by peer

### ISSUE THREAD

**Issue by Noone2018b** [Marginal/docker-get_iplayer#5]
I got a wget error on build at the AtomicParsley download stage, which seems to be related to an Alpine version issue, and was fixed by adding a certificates update as per https://github.com/Yelp/dumb-init/issues/73#issuecomment-240439732.

Just putting it here in case anyone else runs into it!

**Comment by Marginal** [comment]
Thanks for the report.
Since you’ve closed this can I assume that the problem was at your end?

**Comment by Noone2018b** [comment]
Well, on the Alpine end it seems, and from the looks of the issue, may come and go with version. 

`uname -r` gives `3.10.105` in my currently running container, although this doesn't seem to match with any of [the current Alpine image tags](https://hub.docker.com/_/alpine?tab=tags), which is a bit odd. 

See https://github.com/Yelp/dumb-init/issues/73 for all the details.
